### ISSUE TITLE
Plugin ZonePracticeLite v3.04-SNAPSHOT generated an exception 

### ISSUE THREAD

**Issue by ghost** [ZoneDevelopement/ZonePractice-Lite#17]
[21:41:34 WARN]: Exception in thread "Craft Scheduler Thread - 1"
[21:41:34 WARN]: Exception in thread "Craft Scheduler Thread - 2"
[21:41:34 WARN]: org.apache.commons.lang.UnhandledException: Plugin ZonePracticeLite v3.04-SNAPSHOT generated an exception while executing task 56
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException: Nodes must be provided.
at org.yaml.snakeyaml.nodes.NodeTuple.<init>(NodeTuple.java:28)
at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:163)
at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:23)
at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156)
at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:23)
at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156)
at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:64)
at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:242)
at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:206)
at org.yaml.snakeyaml.Yaml.dump(Yaml.java:181)
at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:40)
at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:103)
at dev.nandi0813.practice.Manager.Profile.ProfileFile.saveFile(ProfileFile.java:183)
at dev.nandi0813.practice.Manager.Profile.ProfileFile.setProfileData(ProfileFile.java:84)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 4 more
[21:41:34 WARN]: org.apache.commons.lang.UnhandledException: Plugin ZonePracticeLite v3.04-SNAPSHOT generated an exception while executing task 46
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException: Nodes must be provided.
at org.yaml.snakeyaml.nodes.NodeTuple.<init>(NodeTuple.java:28)
at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:163)
at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:64)
at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:242)
at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:206)
at org.yaml.snakeyaml.Yaml.dump(Yaml.java:181)
at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:40)
at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:103)
at dev.nandi0813.practice.Manager.Profile.ProfileFile.saveFile(ProfileFile.java:183)
at dev.nandi0813.practice.Manager.Profile.ProfileFile.setProfileData(ProfileFile.java:84)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 4 more

**Comment by sprytex** [comment]
@Nandi0813

**Comment by sprytex** [comment]
@Nandi0813 remove this i fixed already
